var nombre=" "
exports.Normalizacion = function(Plb){
    Plb=Plb.normalize('NFD').toLowerCase().replace(/[\u0300-\u036f]/g, '').replace(/[.]/g,'').replace('b','v').replace('z','s')
    let L0=[0];
    let L1=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','t','s','u','v','w','x','y','z'];
    let L2=['le','en','el','al','si','no','mi','de','la','su','es','un','ha','ya','lo','se','mx','me','tu']
    let L3=['con','los','del','soy','que','sea','fue','gob','una','las','pdf','por','vez','son','sin','han','aqv','ser','dar','web','ese','etc','mas','asi','mis','ver','jsf','dia','rol','sus','dan','uno','iii','dos','ano','esa','cvu','sni']
    let L4=['dias','algo','como','cual','para','clic','este','tipo','pais','link','caso','spam','siga','cabo','azul','esta','area','issn','toda','ello','debe','esto','alta','otro','diez','pero','sera','cada','siat','ante','haya','lado','solo','miic','bien','debo','todo','anos','obra','sean','hora','alto','sola','usan','base','dado','beca','hola','menu','curp']
    let L5=['saber','puedo','temas','estoy','pasos','clave','unica','tenga','linea','sobre','boton','nunca','tenia','nuevo','robot','desde','https','nueva','carta','tinta','copia','podra','desea','donde','autor','puede','estan','todas','estos','texto','campo','pegar','tiene','datos','favor','llene','razon','misma','poder','notas','algun','medio','ahora','nivel','dando','dicha','menor','tener','antes','movil','abrir','llave','hacer','parte','icono','forma','lista','pueda','mismo','usted','envio','menos','estar','deben','tengo','citas','anexe','elegi','tesis','grado','deseo','legal','casos','haber','hayas','todos','fondo','color','verde','esten','bases','fecha','libro','etapa','hasta','siete','seran','resto','desee','hayan','llega','envia','tecla','error','becas','firma','salir']
    let L6=['buenos','ayudar','quiero','contar','activo','debera','pagina','nuevos','cuenta','tenido','cuento','marcar','campos','marque','nombre','enviar','centro','llevar','cambio','simple','motivo','actual','anexar','cedula','acepta','libros','dentro','seguir','copiar','numero','llenar','google','social','aplica','partir','primer','mexico','alumno','tratar','cumple','cuatro','cuando','oficio','opcion','ningun','editar','genere','verla,','tengan','estado','adeudo','buscar','obtuvo','manera','cuales','inclui','evalue','cierre','tamano','maximo','pueden','cubrir','avalar','alguna','limite','querer','sujeto','podran','global','fisica','cambia','traves','perish','origen','dichos','poseer','minimo','senala','grados','volver','codigo','accion','acceso','s.n.i.','firmar','correo','scopus','inicio',,'firmas']
    let L7=['cambiar','obtener','ingrese','seccion','sistema','proceso','casilla','aceptar','validar','indicar','enviara','bandeja','entrada','carpeta','palabra','capturo','momento','activar','soporte','tecnico','capture','redacte','formato','firmada','oficial','legible','digital','muestre','permite','guardar','aparece','agregar','empresa','permita','existan','funcion','guiones','deberse','autores','primero','acentos','ejemplo','pediran','adecuar','consejo','ciencia','centros','federal','colocar','muestra','mensaje','estatus','embargo','algunas','iniciar','digitos','intento','posible','privada','ninguna','reporte','tramite','recibio','derecha','deseado','ubicado','columna','captura','postula','termino','realice','cumplan','vigente','generar','periodo','lectivo','informe','despues','becario','enviado','editado','ponerse','mozilla','derecho','alumnos','correos','numeros','incluir','patente','revisar','paginas','archivo','trabajo','scholar','science','tambien','llamado','publish','enviada','cuenten','adeudos','espacio','evaluar','estaran','marcada','medicos','cumplir','tarjeta','deberan','senalar','acuerdo','ultimas','esperar','laboral','firefox','copiado','pegarlo','utiliza','firmado','obtengo','usuario','conacyt','thomson','ingreso','inicial']
    let L8=['presiona','realizar','ingresar','superior','apartado','anterior','presione','recuerda','obtendra','nacional','mostrara','pantalla','correcto','correcta','buscarlo','deseados','completo','atendera','contener','telefono','contacto','oficinas','mediante','utilizar','buscador','articulo','catalogo','marcados','capturar','guardado','habilite','empresas','registre','ejemplos','etcetera','postular','requiere','corregir','convenio','intentar','confirme','activada','programa','acciones','posgrado','cambiara','borrador','reciente','colocado','conocera','consulta','necesita','regresar','devolver','requiera','adecuada','vigencia','requiero','comienza','concluye','activara','rechazar','contario','explorer','recuadro','becarios','imprimir','indicado','enviados','producto','archivos','adjuntar','coincide','adecuado','paquetes','subiendo','amarillo','habiendo','vertical','legibles','busqueda','trabajos','software','enviarla','estricto','dictamen','aparecen','muestran','patentes','aquellos','senalada','acredite','expedida','obtenido','estimulo','personas','bancaria','tramites','proyecto','internet','inferio','usuarios','registro','recuerdo','sistemas','retornar']
    let L9=['necesario','siguiente','poblacion','principal','servicios','continuar','senalados','contrario','confirmar','registrar','indicando','pasaporte','enviarlas','secciones','colocando','articulos','asterisco','capturado','fundacion','generales','validarla','documento','programas','escaneada','aspirante','encuentra','criterios','academico','bloqueado','consultar','capturada','presionar','completar','requisito','completos','recuperar','encuentre','contactar','pendiente','concluido','posterior','desempeno','operadora','encontrar','direccion','capitulos','localizar','percatado','solicitar','doctorado','concursar','obtencion','ocasiones','situacion','publicada','verificar','contenida','recibiran','adjuntado','productos','presenten','facilitar','sugerimos','ordenadas','prestigio','sometidas','concluida','megabytes','destinado','evaluados','destacada','presentar','instituto','migracion','requerido','favorable','economico','reingreso','izquierdo','mostraran','recepcion','habilitan','solicitud']
    let L10=['siguientes','preguntara','seleccione','selecciono','validacion','capturelos','nacimiento','recomienda','fotografia','documentos','diferentes','capturando','correccion','caracteres','especiales','formulario','disponible','importante','nacionales','extranjera','especifica','mencionado','adjuntando','membretado','informamos','tecnologia','facultades','institutos','pertenecen','requeridas','actualizar','requeridos','formalizar','liberacion','establezca','conformada','encontrado','realizados','anteriores','relevantes','necesarias','incompleta','visualizar','postularlo','aspirantes','capturados','telefonico','pendientes','extranjero','peoplesoft','obtuvieron','ingresando','automatiza','registrada','produccion','finalizado','probatorio','reapertura','desarrollo','participar','residencia','resultados','cientifica','evaluacion','existentes','comisiones','consideren','adjuntarse','asegurarse','completado','plataforma','probatoria','encuentren','presentado','explicando','publicadas','unicamente','concedidas','constancia','destacados','claramente','reglamento','solicitado','publicados','realizando','bloqueados','contrasena','registrado','curriculum']
    let L11=['informacion','identifique','presionando','seleccionar','identificar','indicandole','presentarla','publicacion','institucion','corresponde','importantes','instruccion','registrando','tecnologico','coordinador','postulacion','contactarme','registrarse','solicitante','solicitudes','solicitados','completadas','comuniquese','encontrarse','terminacion','navegadores','comunicarse','contactanos','telefonicos','digitalizar','adscripcion','tecnologica','debidamente','probatorios','orientacion','establecida','editoriales','desarrollos','presentados','desplegaran','disposicion','adicionales','especificos','comprobante','establecido','consecutiva','designacion','cancelacion','restablecer','corresponda','electronica','electronico']
    let L12=['relacionados','nacionalidad','continuacion','directamente','obligatorios','incorporando','verificacion','tecnologicos','convocatoria','complementar','coordinacion','correcciones','modificacion','recomendamos','electronicos','contactarlos','conocimiento','investigador','equivalentes','considerados','otorgamiento','preferencial','equivalencia','presentacion','nombramiento','notificacion','alfanumerica']
    let L13=['inhabilitados','universidades','instituciones','anteriormente','convocatorias','departamentos','inconveniente','postulaciones','instrucciones','correctamente','procedimiento','formalizacion','liberacion/no','documentacion','investigacion','participacion','actualizacion','beneficiarios']
    let L14=['autografamente','identificacion','modificaciones','investigadores','dictaminadoras','sobresalientes','posteriormente']
    let L15=['caracteristicas','correspondiente','internacionales']
  
    let LT=[L0,L1,L2,L3,L4,L5,L6,L7,L8,L9,L10,L11,L12,L13,L14,L15];

    Plb=String(Plb).split(' ')
    let PhrF=[]
    for(let i in Plb){
      Nombres(Plb[i])
      let WorldF=Plb[i]
      let Mx=0;
      let V=[0,0,0];
      let lPlb=Plb[i].length
      for(let D=-Math.round(lPlb/4);D<=Math.round(lPlb/4);D++){
        if(D<0){V=[1,0,lPlb+D,]}
        else{V=[0,1,lPlb]}
        for(let d=0;d<=Math.abs(D);d++){
          for(let e in LT[lPlb+D]){
            let SL=0;
            let homofonas=String(LT[lPlb+D][e]).replace('b','v').replace('z','s')
            for(let L=0;L<V[2];L++){
              if(Plb[i][L+d*V[0]]==homofonas[L+d*V[1]]){
                SL++}}
            if(SL/(lPlb+D)>=0.667 &&  SL/(lPlb+D)>=Mx){
              Mx=SL/(lPlb+D)*Math.pow(Math.E,-(Math.pow(D,2)/(2*Math.pow(lPlb/4,2))  ))//Math.pow(Math.E,-(pow(D,2))/(2*pow(lPlb/4,2)))
              WorldF=LT[lPlb+D][e]}}}}
      PhrF.push(WorldF)}
    return PhrF;
}

function Nombres(TextFBN){
  /*
  TextFBN=TextFBN.charAt(0).toUpperCase().concat(TextFBN.substring(1, TextFBN.length))
  let TNombresH=["Hugo","Martin","Lucas","Mateo","Leo","Daniel","Alejandro","Pablo","Manuel","Alvaro","Adrian","David","Mario","Enzo","Diego","Marcos","Izan","Javier","Marco","Alex","Bruno","Oliver","Miguel","Thiago","Antonio","Marc","Carlos","Angel","Juan","Gonzalo","Gael","Sergio","Nicolas","Dylan","Gabriel","Jorge","Jose","Adam","Liam","Eric","Samuel","Dario","Hector","Luca","Iker","Amir","Rodrigo","Saul","Victor","Francisco","Ivan","Jesus","Jaime","Aaron","Ruben","Ian","Guillermo","Erik","Mohamed","Julen","Luis","Pau","Unai","Rafael","Joel","Alberto","Pedro","Raul","Aitor","Santiago","Rayan","Pol","Nil","Noah","Jan","Asier","Fernando","Alonso","Matias","Biel","Andres","Axel","Ismael","Marti","Arnau","Imran","Luka","Ignacio","Aleix","Alan","Elias","Omar","Isaac","Youssef","Jon","Teo","Mauro","Oscar","Cristian","Leonardo","Abel","Adrian","Alejandro","Angel","Carlos","Cesar","Bruno","Daniel","Dario","David","Diego","Emilio","Fabian","Felipe","Gabriel","Hector","Hugo","Jacobo","Jaime","Joaquin","Juan","Leonardo","Leo","Lucas","Marcos","Martin","Mateo","Matias","Miguel","Nicolas","Pablo","Raul","Samuel","Santiago","Sebastian","Tomas","Tristan","Joan","Andres","Ricardo","Manuel","Ezequiel","Francisco","Elias","Blas","Alfonso","Ulises","Gerardo",
  "Alfredo","Alvaro","Amadeo","Amancio","Antonio","Baltasar","Beltran","Benito","Rufino","Boris","Camilo","Ciro","Conrado","Donato","Florentino","Saturnino","Segundo","Anastasio","Cipriano","Teofilo","Casimiro","Bonifacio","Victorino","Eleuterio","Urbano","Severino","Inocencio","Primitivo","Bautista","Agapito","Benedicto","Enrique","Eugenio","Estanislao","Fausto","Faustino","Felipe","Felix","Fermin","Francisco","Gaspar","Genaro","Hilario","Hugo","Ignacio","Ireneo","Ismael","Joaquin","Jose","Juan","Julian","Justo","Leopoldo","Leon","Lisandro","Lorenzo","Lucas","Manuel","Mateo","Pedro","Pio","Romeo","Roque","Rufino","Santiago","Salvador","Simon","Valentin","Valentino","Vicente","Victor","Abundio","Ambrosio","Aniceto","Anselmo","Apolonio","Aquilino","Arsenio","Atanasio","Atilano","Avelino","Bartolo","Basilio","Baudilio","Benigno","Buenaventura","Calixto","Celedonio","Cirilo","Clemente","Conrado","Crisostomo","Crispin","Crispulo","Dionisio","Eliodoro","Eliseo","Emerico","Emeterio","Epifanio","Eufrasio","Eulogio","Feliciano","Florencio","Froilan","Fructuoso","Frutos","Gregorio","Gumersindo","Hermenegildo","Herminio","Higinio","Hipolito","Indalecio","Isidoro","Laureano","Leandro","Leocadio","Leovigildo","Lope","Macario","Meliton","Nemesio","Nicanor",
  "Niceto","Nicomedes","Odon","Orencio","Pantaleon","Patricio","Perfecto","Petronilo","Policarpo","Polonio","Prudencio","Regino","Remigio","Romulo","Ruperto","Sandalio","Serapio","Servando","Silvestre","Sinforoso","Sofronio","Telesforo","Tiburcio","Toribio","Ulpiano","Valeriano","Venancio","Victoriano","Zoilo","Abdon","Abilio","Acacio","Adalberto","Adolfo","Afrodisio","Agabo","Albino","Alcibiades","Amalio","Amasvindo","Amelio","Amonario","Antelmo","Antioco","Antenor","Argimiro","Darek","Enrique","Osiel","Samuel","Adan","Azarias","Gabriel","Kerr","Oliphant","Uzziel","Noe","Abel","Abihail","A,ki,til","Alcibiades","Azai","Azubuike","Baladeva","Booz","Bricio","Emery","Everaldo","Fergal","Hipocrates","Kon","Jaaziel","Jaret","Meginhard","Michio","Obelix","Oier","Olegario","Otoniel","Ozias","Oziel","Qiang","Tyre","Aubrey","Chelem","Chinweike","Iyad","Jigme","Kanda","Meinardo","Osvaldo","Socrates","Thilo","Walter","Armando","Hariman","Fynn","Ricardo","Bernardo","Duncan","Gunther","Leo","Olegario","Odin","Ivar","Archie","Alejandro","Gerardo","Humberto","Alan","Alano","Albano","Aldahir","Allen","Alucio","Ambiorix","Arlen","Artai","Arturo","Artus","Avon","Bardo","Belenos","Belenus","Beloveso","Brayan","Brian","Brenan","Brent","Breogan","Briccio","Carataco",
  "Casey","Cearbhall","Cedrick","Sedrik","Cernunnos","Cuchulain","Dagda","Dailin","Daly","Declan","Dilan","Diviciaco","Donaldo","Donardo","Douglas","Druso","Dugan","Eamon","Eirian","Elbio","Erwin","Esus","Fergie","Finn","Flocelo","Floyd","Gaela","Gallagher","Galvan","Gannicus","Garnik","Glen","Gordon","Gwyddyon","Herve","Idris","Inigo","Kalen","Kellan","Kelvin","Kendall","Kenneth","Kenny","Kerman","Kevin","Kilian","Lennox","Lug","Maddox","Mael","Manannan","Marvin","Melvin","Merlin","Morgan","Neil","Niall","Nelson","Nuada","Ogmios","Oscar","Ossian","Owen","Quillan","Quinn","Rafferty","Ronan","Sayer","Serbal","Sucellos","Taranis","Tristan","Viriato","Vicente","Rodrigo","Marcos","Fernando","Roberto","Carlos","Raul","Marcelo","Fermin","Cesar","Ernesto","Alexander","Mateo","Daniel","Pablo","Alvaro","Adrian","David","Diego","Javier","Mario","Sergio","Marcos","Manuel","Martin","Jorge","Ivan","Carlos","Miguel","Lucas","Santiago","Matias","Angel","Gabriel","Simon","Thiago","Valentin","Julian","Benjamin","Erick","Sasha","Dante","Enzo","Silas","Marco","Andrea","Ariel","Orfeo","Jason","Hector","Aquiles","Adonis","Apolo","Dionisio","Ulises","Hercules","Hipolito","Tristan","Zeus","Adal","Adel","Adriel","Alonso","Amaru","Asher","Azai","Basil","Bastian","Ciro",
  "Corban","Daire","Dante","Dorian","Duncan","Egan","Einar","Elian","Emile","Endor","Ezra","Farid","Fionn","Gadiel","Gael","Goran","Guido","Hasani","Ian","Ilan","Ivar","Joel","Julian","Kadet","Kai","Karim","Kilian","Kuno","Lars","Lavi","Leonel","Lisandro","Luc","Malik","Marius","Milos","Mosi","Nadir","Naim","Normand","Oliver","Oriel","Otto","Pavel","Pax","Piero","Raziel","Rune","Sander","Sinhue","Tadeo","Teo","Tristan","Umi","Uriel","Yael","Yerik","Zaid","Adam","Agustin","Aitor","Alan","Alberto","Alejandro","Alfonso","Alfredo","Antonio","Asier","Axel","Baltasar","Bautista","Benicio","Biel","Bruno","Cesar","Cristian","Domingo","Dylan","Eduardo","Enrique","Erik","Ernesto","Fabio","Felipe","Felix","Fermin","Adal","Adrien","Aketx","Alatz","Aldan","Alec","Alessio","Andeka","Andros","Aomar","Aris","Armengol","Arnulfo","Asel","Auritz","Bayron","Bieito","Brandon","Calvin","Daren","Defin","Demian","Domingo","Dominic","Drako","Edey","Eneas","Enetz","Fabrizio","Felix","Guiem","Guiu","Gus","Hadrian","Hermes","Homero","Igor","Igotz","Ilian","Isacio","Jacques","Jael","Jano","Kerizo","Levi","Lian","Lorenzo","Luca","Maiol","Manoel","Marvin","Mateo","Matias","Maurino","Max","Maximo","Milan","Milo","Mirko","Nils","Otto","Raico","Ramos","Roman","Roque","Seneca",
  "Thor","Xanti","Yone","Adam","Alex","Amaro","Andrea","Archie","Axel","Asher","Basil","Biel","Bran","Bruno","Ciro","Daire","Dante","Dario","Daryl","Dylan","Einar","Elian","Enzo","Erik","Ezra","Fionn","Gael","Goran","Guido","Hugo","Ian","Iker","Ilan","Ivar","Izan","Joel","Jordan","Kamal","Karim","Kenai","Kendall","Kuno","Luc","Lucas","Lavi","Leo","Leon","Liam","Mael","Malik","Marc","Marco","Martin","Milan","Mosi","Nadir","Neo","Neymar","Nil","Oliver","Oriel","Orson","Paris","Rayan","Said","Sasha","Silas","Taranis","Taylor","Teo","Theo","Thiago","Umi","Urko","Van","Viggo","Yael","Yonatan","Zaid","Zyan","Alejandro","Diego","Adrian","Alvaro","Pablo","Daniel","Giuseppe","Napoleon","Jacobo","Astor","Doug","Ren","Stimpy","Carel","Gerard","Enaut","Bittor","Victor","Hugo","Albert","Gabriel","Oscar","Bastian","Harry","Peter","Hansel","Abel","Agni","Blas","Cosme","Damian","Elio","Esau","Fidel","Gaspar","Hector","Hernan","Ivan","Jaime","Keanu","Melchor","Noe","Oto","Pio","Prakash","Brais","Iago","Anxo","Anton","Xoel","Roi","Alexandre","Xabier","Xian","Lois","Breixo","Andre","Xoan","Xavier","Xurxo","Breogan","Denis","Paulo","Nuno","Uxio","Martino","Xavi","Xose","Xabi","Xacobe","Artai","Eloi","Xan","Aldan","Cibran","Marc","Leo","Alex","Jan","Nil","Pol","Adiran","Aitor","Albin","Andoni","Ander","Antxon","Aratz","Ardaitz","Argi","Argider","Aritz","Arnaut","Artur","Asteri","Baladi","Baltz","Bazkoare","Beraun","Bernat","Bikendi","Biktor","Dabi","Dari","Dogartzi","Damen","Dunixi","Edorta","Eki","Ekaitz","Eladi","Elixi","Emiri","Endrike","Eritz","Etor","Euken","Ferran","Frantzes","Frantzisko","Ganiz","Gari","David","Amador","Harsal","Romeo","Valentin","Erasmo","Eros","Amadis","Tadeo","Paris","Amadeo","Amado","Aziz","Darrell","Daryl","Davet","Davis","Dawit","Felipe","Habib","Kelvin","Lennon","Milos","Riku","Valentiniano","Valentino","Adir","Carwyn","Can","Connolley","Krishna","Jeb","Erasmus","Milan","Tristan","Antonio","Calixto","Connor","Timoteo","Ville","Agapi","Amori","Ehud","Gaara","Mishka","Rudo","Heathcliff","Fitzwilliam","Charles","Florentino","Pedro","Armando","Robert","Felix","Ricardo","Gines","Maximo","Cesar","Alfredo","Eugenio","Blas","Gerardo","Nicolas","Aiko","Anwyl","Amias","Davi","Dilber","Gerwyn","Jaimin","Jed","Kiefer","Layden","Lowell","Luben","Navid","Raman","Sevilin","Taavi","Wilmer","Yadid","Oliver","Santiago","Rodrigo","Dorian","Holden","Alonso","Julio","Hector","Leon",
  "Ramon","Robin","Mario","Gustavo","Jacinto","Tristan","Jack","Edward","Liesl","Henry","Wesley"]
  let TNombresM=["Sofia","Lucia","Maria","Paula","Daniela","Valeria","Julia","Alba","Claudia","Isabella","Romina","Jimena","Emma","Irene","Martina","Sara","Laura","Charlotte","Violet","Eleanor","Lucy","Evelyn","Adeline","Alice","Adelaide","Elizabeth","Samantha","Scarlett","Amalia","Olivia","Isla","Ava","Cora","Lucy","Chloe","Renata","Camila","Regina","Dulce","Veronica","Alessandra","Alessia","Alfonsina","Antonella","Bianca","Carina","Chiara","Fiorella","Francesca","Gabriella","Gianna","Lorenza","Marena","Mellea","Nicoletta","Orazia","Pia","Stella","Zinerva","Azahara","Farah","Fatima","Habiba","Halima","Kalila","Karima","Malika","Nayla","Rada","Sabira","Salma","Samira","Zaida","Zara","Pandora","Ariadna","Fedra","Casandra","Helena","Electra","Leda","Penelope","Antigona","Calipso","Andromeda","Ada","Amelia","Carlota","Catalina","Clara","Emilia","Frida","Manuela","Marie","Olimpia","Victoria","Rosa","Rita","Dian","Valentina"]
  if(TNombresH.includes(TextFBN)){nombre=TextFBN;}
  if(TNombresM.includes(TextFBN)){nombre=TextFBN;}*/
}

exports.Nombres = function (){
  return nombre
}