version: '3'
services:
  bot-app:
    image: danimaniarqsoft/bot:${BOT_TAG}
    restart: always
    environment:
      - MONGO_URI=mongodb://kbase-db:27017
      - MONGO_KB_URI=mongodb://kbase-db:27017/chatbot
      - USER_SERVICE=default
      - TZ=America/Mexico_City
      - DISABLE_STATE_STORAGE=${DISABLE_STATE_STORAGE}
      - DISABLE_ANALYTICS=${DISABLE_ANALYTICS}
      - CACHE_TTL=${CACHE_TTL}
      - BOT_LOGGER_LEVEL=info
      - BOT_DB_CORE_LOGGER_LEVEL=info
      - BOT_DB_KBASE_LOGGER_LEVEL=info
    ports:
      - 3000:3000
    depends_on:
    - kbase-db
  kbase-app:
    container_name: 'kbase-app'
    image: danimaniarqsoft/kbase:${KBASE_TAG}
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://kbase-db:27017
      - SPRING_DATA_MONGODB_DATABASE=chatbot
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
    depends_on:
    - kbase-db
  kbase-db:
    container_name: 'kbase-db'
    image: mongo:3.6.14
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
    command: mongod --smallfiles --logpath=/dev/null # --quiet
